// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvmppltgxcpqxztgreoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2bXBwbHRneGNwcXh6dGdyZW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTkxOTIsImV4cCI6MjA1OTA3NTE5Mn0.2i5fWEuw9LbRl1qIvNBY0ieqnreJtP8FvsGIAE21gvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);